import React,{useEffect,useMemo,useState} from 'react'
import { Capacitor } from '@capacitor/core'
import { loadAllDatasets,loadConnections,saveDataset,saveProviderCredentials,appendActivity,loadActivity } from './storage.js'
import { parseAdif,recordToAdif,consolidate,buildQsl,buildIssues,hrdlogPlan,matchRecords } from './core.js'
import { fetchQRZ,fetchWRL,fetchClubLog,fetchEQSL,fetchEQSLInbox,fetchLoTW,pushHRDLog,testProvider,REMOTE_CAPABILITIES,addRemote,updateRemote,deleteRemote } from './providers.js'

const KEYS=['QRZ','WRL','CLUBLOG','EQSL','EQSL_INBOX','LOTW','HRDLOG','HRD']
const LOGS=['QRZ','WRL','CLUBLOG','EQSL','HRDLOG','HRD']
const LABELS={QRZ:'QRZ',WRL:'World Radio League',CLUBLOG:'Club Log',EQSL:'eQSL OutBox',EQSL_INBOX:'eQSL Inbox',LOTW:'LoTW',HRDLOG:'HRDLog.net',HRD:'Ham Radio Deluxe'}
const SHORT={QRZ:'QRZ',WRL:'WRL',CLUBLOG:'CL',EQSL:'eQ',EQSL_INBOX:'eQ+',LOTW:'LoTW',HRDLOG:'HL',HRD:'HRD'}
const FIELDS={
 QRZ:[['api_key','QRZ Logbook API Key','password']],
 WRL:[['api_key','Developer API Key','password'],['logbook_id','Logbook ID (opcional)','text']],
 CLUBLOG:[['email','E-mail','email'],['app_password','Application Password','password'],['callsign','Indicativo','text'],['api_key','API Key de escrita','password']],
 EQSL:[['username','Indicativo / Username','text'],['password','Senha','password'],['qth_nickname','QTH Nickname (opcional)','text']],
 LOTW:[['login','Login LoTW','text'],['password','Senha LoTW','password']],
 HRDLOG:[['callsign','Indicativo','text'],['upload_code','Upload Code','password']],
}
const fmt=n=>Number(n||0).toLocaleString('pt-BR')
const when=v=>v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Nunca'
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
function configured(p,c){if(p==='EQSL_INBOX')p='EQSL';if(p==='HRD')return false;const x=c[p]||{};if(p==='QRZ'||p==='WRL')return!!x.api_key;if(p==='CLUBLOG')return!!(x.email&&x.app_password&&x.callsign);if(p==='EQSL')return!!(x.username&&x.password);if(p==='LOTW')return!!(x.login&&x.password);if(p==='HRDLOG')return!!(x.callsign&&x.upload_code);return false}
function Badge({children,tone=''}){return <span className={'m9-badge '+tone}>{children}</span>}
function Btn({children,kind='',small=false,...props}){return <button className={'m9-btn '+kind+(small?' small':'')} {...props}>{children}</button>}
function Empty({children}){return <div className="m9-empty">{children||'Nada para mostrar.'}</div>}
async function shareText(name,text,mime='text/plain'){const file=new File([text],name,{type:mime});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:name});return}const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function SourceSheet({provider,connections,onClose,onSaved}){
 const key=provider==='EQSL_INBOX'?'EQSL':provider,[values,setValues]=useState(connections[key]||{}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function save(test){setBusy(true);setMsg('');try{const all=await saveProviderCredentials(key,values);if(test)setMsg(await testProvider(provider==='EQSL_INBOX'?'EQSL':provider,all[key]));else setMsg('Salvo com segurança.');await appendActivity('CONNECTION',LABELS[provider]+' configurado',{provider});await onSaved(all)}catch(e){setMsg('Erro: '+e.message)}finally{setBusy(false)}}
 return <div className="m9-sheet-bg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="m9-sheet"><div className="m9-grabber"/><header><div><small>CONEXÃO</small><h2>{LABELS[provider]}</h2></div><button onClick={onClose}>×</button></header>{provider==='EQSL_INBOX'&&<p className="m9-hint">O Inbox usa a mesma conta do eQSL OutBox.</p>}<div className="m9-fields">{(FIELDS[key]||[]).map(f=><label key={f[0]}><span>{f[1]}</span><input type={f[2]} value={values[f[0]]||''} onChange={e=>setValues({...values,[f[0]]:e.target.value})}/></label>)}</div>{msg&&<div className={'m9-message '+(msg.startsWith('Erro')?'error':'')}>{msg}</div>}<div className="m9-sheet-actions"><Btn kind="ghost" disabled={busy} onClick={()=>save(true)}>Testar</Btn><Btn disabled={busy} onClick={()=>save(false)}>Salvar</Btn></div></section></div>
}
function ActionSheet({rows,selected,datasets,connections,onClose,onDone}){
 const chosen=rows.filter(x=>selected.has(x.id))
 const addTargets=Object.entries(REMOTE_CAPABILITIES).filter(([p,c])=>c.add&&configured(p,connections)).map(x=>x[0]),deleteSources=Object.entries(REMOTE_CAPABILITIES).filter(([p,c])=>c.delete&&configured(p,connections)).map(x=>x[0])
 const [mode,setMode]=useState('publish'),[target,setTarget]=useState(addTargets[0]||'QRZ'),[source,setSource]=useState(deleteSources[0]||'WRL'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[changes,setChanges]=useState({})
 async function execute(){
  setBusy(true);setMsg('');let ok=0,fail=0,hrdAdded=[]
  try{
   if(mode==='export'){await shareText('qso-manager-selecao.adi',chosen.map(x=>recordToAdif(x.canonical)).join('\n'),'text/plain');ok=chosen.length}
   else for(const q of chosen){
    try{
     if(mode==='publish'){if(q.refs[target]!=null)continue;await addRemote(target,connections[target],q.canonical);if(target==='HRDLOG')hrdAdded.push(q.canonical)}
     if(mode==='delete'){const idx=q.refs[source];if(idx==null)throw new Error('QSO não existe em '+source);await deleteRemote(source,connections[source],datasets[source].records[idx])}
     if(mode==='update'){const idx=q.refs.WRL;if(idx==null)throw new Error('QSO não existe no WRL');await updateRemote('WRL',connections.WRL,datasets.WRL.records[idx],changes)}
     ok++
    }catch(e){fail++;console.warn('bulk',q.call,e)}
   }
   if(hrdAdded.length){
    const old=datasets.HRDLOG||{records:[],metadata:{}}
    await saveDataset('HRDLOG',{records:[...(old.records||[]),...hrdAdded],updatedAt:new Date().toISOString(),metadata:{...(old.metadata||{}),source:'bootstrap_plus_online'}})
   }
   await appendActivity('BULK',mode+' em '+chosen.length+' QSO(s)',{mode,target,source,ok,fail},fail?'PARTIAL':'OK');setMsg(ok+' concluído(s) · '+fail+' erro(s).');await onDone(mode==='export'?[]:[target,source,'WRL'])
  }catch(e){setMsg('Erro: '+e.message)}finally{setBusy(false)}
 }
 return <div className="m9-sheet-bg"><section className="m9-sheet"><div className="m9-grabber"/><header><div><small>AÇÃO EM LOTE</small><h2>{chosen.length} QSO(s)</h2></div><button onClick={onClose}>×</button></header><div className="m9-segments">{[['publish','Enviar'],['update','Editar WRL'],['delete','Excluir'],['export','Exportar']].map(x=><button className={mode===x[0]?'active':''} key={x[0]} onClick={()=>setMode(x[0])}>{x[1]}</button>)}</div>{mode==='publish'&&<label className="m9-select"><span>Destino</span><select value={target} onChange={e=>setTarget(e.target.value)}>{addTargets.map(p=><option key={p}>{LABELS[p]}</option>)}</select></label>}{mode==='delete'&&<label className="m9-select"><span>Excluir de</span><select value={source} onChange={e=>setSource(e.target.value)}>{deleteSources.map(p=><option key={p}>{LABELS[p]}</option>)}</select></label>}{mode==='update'&&<div className="m9-edit-grid">{['RST_SENT','RST_RCVD','GRIDSQUARE','STATE','COMMENT','NAME','QTH'].map(k=><label key={k}><span>{k}</span><input value={changes[k]||''} onChange={e=>setChanges({...changes,[k]:e.target.value})} placeholder="sem mudança"/></label>)}</div>}{mode==='export'&&<p className="m9-hint">Gera um ADIF com os QSOs selecionados para compartilhar ou salvar no aparelho.</p>}{msg&&<div className={'m9-message '+(msg.startsWith('Erro')?'error':'')}>{msg}</div>}<div className="m9-sheet-actions"><Btn kind="ghost" onClick={onClose}>Fechar</Btn><Btn disabled={busy||!chosen.length} onClick={execute}>{busy?'Executando…':'Executar'}</Btn></div></section></div>
}
function DetailSheet({q,datasets,connections,onClose,onDone}){
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const missing=q.missingIn.filter(p=>REMOTE_CAPABILITIES[p]?.add&&configured(p,connections))
 async function publish(p){setBusy(true);try{await addRemote(p,connections[p],q.canonical);if(p==='HRDLOG'){const old=datasets.HRDLOG||{records:[],metadata:{}};await saveDataset('HRDLOG',{records:[...(old.records||[]),q.canonical],updatedAt:new Date().toISOString(),metadata:{...(old.metadata||{}),source:'bootstrap_plus_online'}})}await appendActivity('PUBLISH',q.call+' enviado para '+p,{provider:p});setMsg('Enviado para '+p);await onDone([p])}catch(e){setMsg('Erro: '+e.message)}finally{setBusy(false)}}
 return <div className="m9-sheet-bg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="m9-sheet"><div className="m9-grabber"/><header><div><small>DETALHE DO QSO</small><h2>{q.call}</h2><p>{q.date} · {q.time.slice(0,4)} UTC · {q.band} · {q.mode}</p></div><button onClick={onClose}>×</button></header><div className="m9-source-badges">{q.providers.map(p=><Badge key={p} tone="ok">{SHORT[p]}</Badge>)}{q.missingIn.map(p=><Badge key={p} tone="warn">− {SHORT[p]}</Badge>)}</div>{q.differences.length>0&&<div className="m9-detail-card"><b>Diferenças</b>{q.differences.map((d,i)=><p key={i}>{d.label}: {Object.entries(d.values).map(x=>x.join('=')).join(' · ')}</p>)}</div>}<div className="m9-detail-card"><b>Ações rápidas</b><div className="m9-action-grid">{missing.map(p=><Btn small key={p} disabled={busy} onClick={()=>publish(p)}>Enviar para {SHORT[p]}</Btn>)}</div></div><div className="m9-detail-card"><b>Valores por fonte</b>{Object.entries(q.refs).map(([p,i])=><div className="m9-record-row" key={p}><Badge>{SHORT[p]}</Badge><code>{JSON.stringify(datasets[p]?.records?.[i]||{})}</code></div>)}</div>{msg&&<div className={'m9-message '+(msg.startsWith('Erro')?'error':'')}>{msg}</div>}</section></div>
}
function CompareTool(){
 const [files,setFiles]=useState([]),[result,setResult]=useState(null)
 async function compare(){const parsed=await Promise.all(files.map(async f=>({name:f.name,records:parseAdif(await f.text())})));const ref=parsed[0];const pairs=parsed.slice(1).map(x=>({name:x.name,...matchRecords(ref.records,x.records,ref.name,x.name)}));setResult({ref,pairs})}
 return <section className="m9-tool"><h2>Comparação avançada</h2><p>Selecione dois ou mais ADIFs. O primeiro é a referência.</p><label className="m9-file-wide">Selecionar ADIFs<input type="file" multiple accept=".adi,.adif,.txt" onChange={e=>setFiles([...e.target.files])}/></label><small>{files.map(f=>f.name).join(' · ')||'Nenhum arquivo'}</small><Btn disabled={files.length<2} onClick={compare}>Comparar</Btn>{result&&<div className="m9-tool-results">{result.pairs.map(p=><article key={p.name}><b>{p.name}</b><span>Pareados {fmt(p.matches.length)}</span><span>Ausentes na referência {fmt(p.unmatchedRight.length)}</span><span>Ausentes no comparado {fmt(p.unmatchedLeft.length)}</span><span>Revisão {fmt(p.reviews.length)}</span></article>)}</div>}</section>
}
function QSLFileTool(){
 const [ref,setRef]=useState(null),[eq,setEq]=useState(null),[lo,setLo]=useState(null),[items,setItems]=useState(null)
 async function run(){const qrz=parseAdif(await ref.text()),e=eq?parseAdif(await eq.text()):[],l=lo?parseAdif(await lo.text()):[];setItems(buildQsl(qrz,e,l))}
 return <section className="m9-tool"><h2>QSL por arquivos</h2><p>Audite confirmações manualmente sem usar QSO_DATE como data de recebimento.</p><div className="m9-tool-files"><label>QRZ<input type="file" accept=".adi,.adif,.txt" onChange={e=>setRef(e.target.files?.[0])}/><small>{ref?.name||'referência'}</small></label><label>eQSL Inbox<input type="file" accept=".adi,.adif,.txt" onChange={e=>setEq(e.target.files?.[0])}/><small>{eq?.name||'opcional'}</small></label><label>LoTW<input type="file" accept=".adi,.adif,.txt" onChange={e=>setLo(e.target.files?.[0])}/><small>{lo?.name||'opcional'}</small></label></div><Btn disabled={!ref||(!eq&&!lo)} onClick={run}>Analisar</Btn>{items&&<div className="m9-tool-results"><article><b>{fmt(items.length)} QSO(s) com evidência</b></article>{items.slice(0,100).map((x,i)=><article key={i}><b>{x.call}</b><span>{x.services.map(s=>s.source+(s.date?' '+s.date:'')).join(' · ')}</span></article>)}</div>}</section>
}

export default function App900(){
 const [tab,setTab]=useState('home'),[more,setMore]=useState(null),[connections,setConnections]=useState({}),[datasets,setDatasets]=useState({}),[activity,setActivity]=useState([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[progress,setProgress]=useState(''),[message,setMessage]=useState(''),[sheet,setSheet]=useState(null),[detail,setDetail]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('ALL'),[selected,setSelected]=useState(new Set()),[actions,setActions]=useState(false)
 async function boot(){const [c,d,a]=await Promise.all([loadConnections(),loadAllDatasets(KEYS),loadActivity()]);setConnections(c);setDatasets(d);setActivity(a);setLoading(false)}
 useEffect(()=>{boot().catch(e=>{setMessage('Erro: '+e.message);setLoading(false)})},[])
 const model=useMemo(()=>{const rows=consolidate(datasets,LOGS),qsls=buildQsl(datasets.QRZ?.records||[],datasets.EQSL_INBOX?.records||[],datasets.LOTW?.records||[]);return{rows,qsls,issues:buildIssues(rows,qsls)}},[datasets])
 const counts=useMemo(()=>Object.fromEntries(['MISSING','DIFFERENCE','DUPLICATE','QSL'].map(k=>[k,model.issues.filter(x=>x.type===k).length])),[model.issues])
 const filteredLog=useMemo(()=>{const q=search.trim().toUpperCase();return !q?model.rows:model.rows.filter(x=>[x.call,x.country,x.grid,x.band,x.mode].join(' ').toUpperCase().includes(q))},[model.rows,search])
 const shownIssues=useMemo(()=>filter==='ALL'?model.issues:model.issues.filter(x=>x.type===filter),[model.issues,filter])
 async function persist(p,r,next){const payload={records:r.records||[],updatedAt:new Date().toISOString(),metadata:r.metadata||{}};await saveDataset(p,payload);next[p]=payload}
 async function refreshProvider(p,next=datasets){const fn={QRZ:fetchQRZ,WRL:fetchWRL,CLUBLOG:fetchClubLog,EQSL:fetchEQSL,EQSL_INBOX:fetchEQSLInbox,LOTW:fetchLoTW}[p];if(!fn)throw new Error('Fonte '+p+' não é sincronizável');const cred=p==='EQSL_INBOX'?connections.EQSL:connections[p],r=await fn(cred);await persist(p,r,next);return r}
 async function syncAll(){if(syncing)return;setSyncing(true);setMessage('');const next={...datasets},errors=[];for(const p of ['QRZ','WRL','CLUBLOG','EQSL','EQSL_INBOX','LOTW']){if(!configured(p,connections))continue;setProgress('Atualizando '+LABELS[p]+'…');try{await refreshProvider(p,next)}catch(e){errors.push(LABELS[p]+': '+e.message)}}try{if(configured('HRDLOG',connections)&&next.HRDLOG?.updatedAt&&next.QRZ?.records?.length){const candidates=hrdlogPlan(next.QRZ.records,next.HRDLOG.records||[]).slice(0,100),known=[...(next.HRDLOG.records||[])];for(let i=0;i<candidates.length;i++){setProgress('HRDLog '+(i+1)+'/'+candidates.length);try{await pushHRDLog(connections.HRDLOG,next.QRZ.records[candidates[i].index]);known.push(next.QRZ.records[candidates[i].index])}catch{}}if(candidates.length){const payload={records:known,updatedAt:new Date().toISOString(),metadata:{source:'bootstrap_plus_online'}};await saveDataset('HRDLOG',payload);next.HRDLOG=payload}}}catch(e){errors.push('HRDLog: '+e.message)}setDatasets(next);setProgress('');setSyncing(false);await appendActivity('SYNC','Atualização de fontes concluída',{errors},errors.length?'PARTIAL':'OK');setActivity(await loadActivity());setMessage(errors.length?'Concluído com '+errors.length+' falha(s): '+errors.join(' | '):'Fontes atualizadas e reconciliadas.')}
 async function syncOne(p){setSyncing(true);setProgress('Atualizando '+LABELS[p]+'…');try{const next={...datasets},r=await refreshProvider(p,next);setDatasets(next);await appendActivity('SYNC',LABELS[p]+' atualizado',{provider:p,records:r.records?.length||0});setMessage(LABELS[p]+': '+fmt(r.records?.length)+' registro(s).')}catch(e){setMessage('Erro: '+e.message)}finally{setProgress('');setSyncing(false)}}
 async function importAdif(p,file){if(!file)return;try{const records=parseAdif(await file.text());if(!records.length)throw new Error('Nenhum QSO válido');const payload={records,updatedAt:new Date().toISOString(),metadata:{source:p==='HRD'?'local_adif':'bootstrap_adif',filename:file.name}};await saveDataset(p,payload);setDatasets({...datasets,[p]:payload});await appendActivity('IMPORT',LABELS[p]+' importado',{provider:p,records:records.length,filename:file.name});setMessage(LABELS[p]+': '+fmt(records.length)+' QSOs importados.')}catch(e){setMessage('Erro: '+e.message)}}
 async function updateHrdlog(){setSyncing(true);try{const candidates=hrdlogPlan(datasets.QRZ?.records||[],datasets.HRDLOG?.records||[]).slice(0,500);if(!candidates.length){setMessage('HRDLog alinhado.');return}const known=[...(datasets.HRDLOG?.records||[])];let ok=0;for(const q of candidates){try{await pushHRDLog(connections.HRDLOG,datasets.QRZ.records[q.index]);known.push(datasets.QRZ.records[q.index]);ok++}catch{}}const payload={records:known,updatedAt:new Date().toISOString(),metadata:{source:'bootstrap_plus_online'}};await saveDataset('HRDLOG',payload);setDatasets({...datasets,HRDLOG:payload});await appendActivity('PUBLISH','HRDLog atualizado',{sent:ok});setMessage('HRDLog: '+ok+' QSO(s) enviados/confirmados.')}finally{setSyncing(false)}}
 async function afterRemote(providers){const next=await loadAllDatasets(KEYS);for(const p of [...new Set(providers||[])])if(['QRZ','WRL','CLUBLOG','EQSL'].includes(p)&&configured(p,connections)){try{await refreshProvider(p,next)}catch{}}setDatasets(next);setActivity(await loadActivity());setSelected(new Set())}
 function toggle(id){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 if(loading)return <div className="m9-splash"><div>PU<br/>BRU</div><h1>QSO Manager</h1><p>Preparando sua estação…</p></div>
 const primary=[['home','Início','⌂'],['log','Log','◎'],['review','Revisar','!'],['qsl','QSL','✓'],['sources','Fontes','◉']]
 return <div className="m9-app"><header className="m9-top"><div><small>PU2BRU</small><h1>QSO Manager <span>v9</span></h1></div><div><button onClick={()=>setMore('menu')}>•••</button><button className={syncing?'spin':''} disabled={syncing} onClick={syncAll}>↻</button></div></header>{progress&&<div className="m9-progress">{progress}</div>}{message&&<div className={'m9-toast '+(message.startsWith('Erro')?'error':'')} onClick={()=>setMessage('')}>{message}<b>×</b></div>}<main>
 {tab==='home'&&<section className="m9-page"><div className="m9-hero"><small>CENTRAL DE OPERAÇÃO</small><h2>{fmt(model.rows.length)}</h2><p>QSOs consolidados</p><div><span><b>{LOGS.filter(p=>datasets[p]?.updatedAt).length}</b> fontes carregadas</span><span><b>{model.qsls.length}</b> com QSL online</span></div></div><h3 className="m9-section">Próxima melhor ação</h3><button className="m9-next" onClick={()=>setTab((counts.MISSING+counts.DIFFERENCE+counts.DUPLICATE)?'review':'log')}><div><b>{(counts.MISSING+counts.DIFFERENCE+counts.DUPLICATE)?'Revisar pendências':'Log reconciliado'}</b><p>{fmt(counts.MISSING)} ausências · {fmt(counts.DIFFERENCE)} diferenças · {fmt(counts.DUPLICATE)} duplicidades</p></div><span>→</span></button><div className="m9-mini-grid"><button onClick={()=>setTab('review')}><b>{fmt(counts.MISSING)}</b><span>Ausentes</span></button><button onClick={()=>setTab('review')}><b>{fmt(counts.DIFFERENCE)}</b><span>Diferenças</span></button><button onClick={()=>setTab('qsl')}><b>{fmt(counts.QSL)}</b><span>QSL</span></button><button onClick={()=>setTab('sources')}><b>{KEYS.filter(p=>datasets[p]?.updatedAt||configured(p,connections)).length}</b><span>Fontes</span></button></div><button className="m9-refresh" disabled={syncing} onClick={syncAll}>↻ <span><b>Atualizar tudo</b><small>Sincronizar APIs e reconciliar</small></span></button></section>}
 {tab==='log'&&<section className="m9-page"><div className="m9-page-title"><small>LOG CONSOLIDADO</small><h2>Seus QSOs</h2><p>Um contato, todas as fontes.</p></div><div className="m9-search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Indicativo, país, grid, banda…"/>{selected.size>0?<button onClick={()=>setActions(true)}>{selected.size} ações</button>:search&&<button onClick={()=>setSearch('')}>×</button>}</div><div className="m9-qso-list">{filteredLog.slice(0,1500).map(q=><article key={q.id} className={selected.has(q.id)?'selected':''}><button className="m9-check" onClick={()=>toggle(q.id)}>{selected.has(q.id)?'✓':'○'}</button><button className="m9-qso-open" onClick={()=>setDetail(q)}><div><h3>{q.call}</h3><p>{q.date} · {q.time.slice(0,4)} UTC</p></div><div className="m9-band"><b>{q.band}</b><small>{q.mode}</small></div><div className="m9-badges">{q.providers.map(p=><Badge key={p} tone="ok">{SHORT[p]}</Badge>)}{q.missingIn.map(p=><Badge key={p} tone="warn">−{SHORT[p]}</Badge>)}</div></button></article>)}</div>{!filteredLog.length&&<Empty>Nenhum QSO encontrado.</Empty>}</section>}
 {tab==='review'&&<section className="m9-page"><div className="m9-page-title"><small>RECONCILIAÇÃO</small><h2>Revisar</h2><p>Somente o que merece decisão.</p></div><div className="m9-chips">{[['ALL','Tudo',model.issues.length],['MISSING','Ausentes',counts.MISSING],['DIFFERENCE','Diferenças',counts.DIFFERENCE],['DUPLICATE','Duplicados',counts.DUPLICATE],['QSL','QSL',counts.QSL]].map(x=><button key={x[0]} className={filter===x[0]?'active':''} onClick={()=>setFilter(x[0])}>{x[1]} <b>{fmt(x[2])}</b></button>)}</div><div className="m9-issue-list">{shownIssues.slice(0,1200).map((x,i)=><article key={i}><i className={x.type.toLowerCase()}>{x.type==='QSL'?'✓':x.type==='MISSING'?'−':'!'}</i><div><h3>{x.call}<span>{x.band} · {x.mode}</span></h3><p>{x.date} {String(x.time||'').slice(0,4)} · {x.message}</p></div></article>)}</div>{!shownIssues.length&&<Empty>Nada para revisar.</Empty>}</section>}
 {tab==='qsl'&&<section className="m9-page"><div className="m9-page-title"><small>CONFIRMAÇÕES</small><h2>QSL</h2><p>eQSL Inbox + LoTW, sem inventar datas.</p></div><div className="m9-qsl-kpis"><div><b>{fmt(model.qsls.length)}</b><span>Confirmados</span></div><div><b>{fmt(model.qsls.filter(x=>x.services.some(s=>s.kind==='LOTW')).length)}</b><span>LoTW</span></div><div><b>{fmt(model.qsls.filter(x=>x.services.some(s=>s.kind==='EQSL')).length)}</b><span>eQSL</span></div></div><div className="m9-qso-list">{model.qsls.slice(0,1200).map((q,i)=><article key={i}><div className="m9-qso-open"><div><h3>{q.call}</h3><p>{q.date} · {q.band} · {q.mode}</p></div><div className="m9-qsl-source">{q.services.map((s,j)=><Badge key={j} tone="ok">{s.source}{s.date?' '+s.date:''}</Badge>)}</div></div></article>)}</div>{!model.qsls.length&&<Empty>Atualize eQSL Inbox e LoTW.</Empty>}<p className="m9-policy">QSO_DATE nunca é usado como data de recebimento da QSL.</p></section>}
 {tab==='sources'&&<section className="m9-page"><div className="m9-page-title"><small>FONTES</small><h2>Conexões e dados</h2><p>A mesma cobertura funcional do desktop, adaptada ao celular.</p></div><div className="m9-source-list">{KEYS.map(p=>{const on=p==='HRD'?!!datasets.HRD?.updatedAt:configured(p,connections),snap=datasets[p]||{},file=['HRD','HRDLOG'].includes(p),sync=!file&&p!=='HRDLOG';return <article key={p}><button className="m9-source-open" onClick={()=>p!=='HRD'&&setSheet(p)}><i className={on?'connected':''}>{SHORT[p]}</i><div><h3>{LABELS[p]}</h3><p>{on?'Pronto':'Não configurado'} · {fmt(snap.records?.length)} registros</p><small>Atualizado: {when(snap.updatedAt)}</small></div><em>{p==='HRD'?'ADIF':'›'}</em></button><div className="m9-source-actions">{file&&<label>Importar/Reconciliar ADIF<input type="file" accept=".adi,.adif,.txt" onChange={e=>importAdif(p,e.target.files?.[0])}/></label>}{sync&&<button disabled={!on||syncing} onClick={()=>syncOne(p)}>Atualizar</button>}{p==='HRDLOG'&&<button disabled={!on||!snap.updatedAt||syncing} onClick={updateHrdlog}>Enviar ausentes</button>}</div></article>})}</div></section>}
 </main><nav className="m9-bottom">{primary.map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>{setTab(x[0]);setMore(null)}}><b>{x[2]}</b><span>{x[1]}</span>{x[0]==='review'&&(counts.MISSING+counts.DIFFERENCE+counts.DUPLICATE)>0&&<i>{counts.MISSING+counts.DIFFERENCE+counts.DUPLICATE>99?'99+':counts.MISSING+counts.DIFFERENCE+counts.DUPLICATE}</i>}</button>)}</nav>
 {sheet&&<SourceSheet provider={sheet} connections={connections} onClose={()=>setSheet(null)} onSaved={async all=>{setConnections(all);setSheet(null)}}/>}{detail&&<DetailSheet q={detail} datasets={datasets} connections={connections} onClose={()=>setDetail(null)} onDone={afterRemote}/>} {actions&&<ActionSheet rows={model.rows} selected={selected} datasets={datasets} connections={connections} onClose={()=>setActions(false)} onDone={afterRemote}/>}
 {more==='menu'&&<div className="m9-sheet-bg" onMouseDown={e=>e.target===e.currentTarget&&setMore(null)}><section className="m9-sheet"><div className="m9-grabber"/><header><div><small>MAIS</small><h2>Ferramentas e sistema</h2></div><button onClick={()=>setMore(null)}>×</button></header><div className="m9-more-grid"><button onClick={()=>setMore('compare')}><b>⇄</b><span>Comparar ADIF</span></button><button onClick={()=>setMore('qslfiles')}><b>✓</b><span>QSL por arquivos</span></button><button onClick={async()=>{setActivity(await loadActivity());setMore('activity')}}><b>◷</b><span>Histórico</span></button><button onClick={()=>setMore('diagnostics')}><b>⊙</b><span>Diagnóstico</span></button></div></section></div>}
 {more&&more!=='menu'&&<div className="m9-full-tool"><header><button onClick={()=>setMore(null)}>←</button><div><small>PU2BRU · QSO MANAGER</small><h2>{more==='compare'?'Comparar ADIF':more==='qslfiles'?'QSL por arquivos':more==='activity'?'Histórico':'Diagnóstico'}</h2></div></header><main>{more==='compare'&&<CompareTool/>}{more==='qslfiles'&&<QSLFileTool/>}{more==='activity'&&<div className="m9-activity">{activity.length?activity.map(x=><article key={x.id}><Badge tone={x.status==='OK'?'ok':'warn'}>{x.kind}</Badge><div><b>{x.summary}</b><small>{when(x.timestamp)}</small></div></article>):<Empty>Nenhuma atividade registrada.</Empty>}</div>}{more==='diagnostics'&&<section className="m9-tool"><h2>Diagnóstico mobile</h2><div className="m9-diagnostic"><div><span>Plataforma</span><b>{Capacitor.getPlatform()}</b></div><div><span>Versão</span><b>9.0.0</b></div><div><span>Fontes configuradas</span><b>{KEYS.filter(p=>configured(p,connections)).length}</b></div><div><span>Datasets carregados</span><b>{KEYS.filter(p=>datasets[p]?.updatedAt).length}</b></div><div><span>QSOs consolidados</span><b>{model.rows.length}</b></div><div><span>Storage</span><b>IndexedDB + Secure Storage</b></div></div></section>}</main></div>}
 </div>
}
