import React, { useEffect, useMemo, useState } from 'react'
import { loadAllDatasets, loadConnections, saveDataset, saveProviderCredentials, appendActivity, loadActivity, exportLocalBackup } from './storage.js'
import { parseAdif, consolidate, buildQsl, buildIssues, hrdlogPlan, recordToAdif, matchRecords } from './core.js'
import { fetchQRZ, fetchWRL, fetchClubLog, fetchEQSL, fetchEQSLInbox, fetchLoTW, pushHRDLog, testProvider } from './providers.js'

const VERSION='9.0.0'
const KEYS=['QRZ','WRL','CLUBLOG','EQSL','EQSL_INBOX','LOTW','HRDLOG','HRD']
const LOGS=['QRZ','WRL','CLUBLOG','EQSL','HRDLOG','HRD']
const LABELS={QRZ:'QRZ',WRL:'World Radio League',CLUBLOG:'Club Log',EQSL:'eQSL OutBox',EQSL_INBOX:'eQSL Inbox',LOTW:'LoTW',HRDLOG:'HRDLog.net',HRD:'Ham Radio Deluxe'}
const SHORT={QRZ:'QRZ',WRL:'WRL',CLUBLOG:'CL',EQSL:'eQ',EQSL_INBOX:'eQ+',LOTW:'LoTW',HRDLOG:'HL',HRD:'HRD'}
const NAV=[['overview','Visão geral','⌂'],['log','Log','◎'],['inbox','Pendências','!'],['qsl','QSL','✓'],['sources','Fontes','◉'],['tools','Ferramentas','⌘']]
const FIELDS={
 QRZ:[['api_key','QRZ Logbook API Key','password']],
 WRL:[['api_key','Developer API Key','password'],['logbook_id','Logbook ID (opcional)','text']],
 CLUBLOG:[['email','E-mail','email'],['app_password','Application Password','password'],['callsign','Indicativo','text'],['api_key','API Key de escrita (opcional)','password']],
 EQSL:[['username','Indicativo / Username','text'],['password','Senha','password'],['qth_nickname','QTH Nickname (opcional)','text']],
 LOTW:[['login','Login LoTW','text'],['password','Senha LoTW','password']],
 HRDLOG:[['callsign','Indicativo','text'],['upload_code','Upload Code','password']],
}
const fmt=n=>Number(n||0).toLocaleString('pt-BR')
const when=v=>v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Nunca'
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
function configured(p,c,datasets={}){if(p==='EQSL_INBOX')p='EQSL';if(p==='HRD')return !!datasets.HRD?.updatedAt;const x=c[p]||{};if(p==='QRZ'||p==='WRL')return !!x.api_key;if(p==='CLUBLOG')return !!(x.email&&x.app_password&&x.callsign);if(p==='EQSL')return !!(x.username&&x.password);if(p==='LOTW')return !!(x.login&&x.password);if(p==='HRDLOG')return !!(x.callsign&&x.upload_code);return false}
function Badge({children,tone=''}){return <span className={'m9-badge '+tone}>{children}</span>}
function Button({children,kind='primary',...props}){return <button className={'m9-btn '+kind} {...props}>{children}</button>}
function Notice({children,tone='info'}){return <div className={'m9-notice '+tone}>{children}</div>}
function Empty({title='Nada por aqui',children}){return <div className="m9-empty"><b>{title}</b>{children&&<p>{children}</p>}</div>}
function download(name,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

function SourceSheet({provider,connections,onClose,onSaved}){
 const key=provider==='EQSL_INBOX'?'EQSL':provider
 const [values,setValues]=useState(connections[key]||{}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function save(test){setBusy(true);setMsg('');try{const all=await saveProviderCredentials(key,values);if(test)setMsg(await testProvider(provider==='EQSL_INBOX'?'EQSL':provider,all[key]));else setMsg('Salvo com segurança.');await appendActivity('CREDENTIAL',`${LABELS[provider]} configurado`);await onSaved(all)}catch(e){setMsg('Erro: '+e.message)}finally{setBusy(false)}}
 return <div className="m9-sheet-bg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="m9-sheet"><div className="m9-grabber"/><header><div><small>CONEXÃO SEGURA</small><h2>{LABELS[provider]}</h2></div><button onClick={onClose}>×</button></header>{provider==='EQSL_INBOX'&&<p className="m9-hint">O Inbox usa a mesma conta do eQSL OutBox.</p>}<div className="m9-fields">{(FIELDS[key]||[]).map(f=><label key={f[0]}><span>{f[1]}</span><input type={f[2]} value={values[f[0]]||''} onChange={e=>setValues({...values,[f[0]]:e.target.value})}/></label>)}</div>{msg&&<Notice tone={msg.startsWith('Erro')?'error':'ok'}>{msg}</Notice>}<div className="m9-sheet-actions"><Button kind="secondary" disabled={busy} onClick={()=>save(true)}>Testar</Button><Button disabled={busy} onClick={()=>save(false)}>Salvar</Button></div></section></div>
}

function DetailSheet({row,datasets,onClose}){
 if(!row)return null
 return <div className="m9-sheet-bg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="m9-sheet detail"><div className="m9-grabber"/><header><div><small>DETALHE DO QSO</small><h2>{row.call}</h2><p>{row.date} · {row.time?.slice(0,4)} UTC · {row.band} · {row.mode}</p></div><button onClick={onClose}>×</button></header><div className="m9-detail-source-list">{Object.entries(row.refs||{}).map(([p,index])=>{const rec=datasets[p]?.records?.[index]||{};return <article key={p}><div><Badge tone={p==='QRZ'?'truth':'ok'}>{SHORT[p]}</Badge><small>{Object.keys(rec).length} campos</small></div><div>{Object.entries(rec).slice(0,40).map(([k,v])=><p key={k}><span>{k}</span><code>{String(v)}</code></p>)}</div></article>})}</div></section></div>
}

function AdvancedCompare(){
 const make=name=>({id:`${Date.now()}-${Math.random()}`,name,file:null});const [sources,setSources]=useState([make('QRZ'),make('HRD')]),[reference,setReference]=useState(0),[result,setResult]=useState(null),[msg,setMsg]=useState('')
 function patch(i,changes){setSources(v=>v.map((x,j)=>j===i?{...x,...changes}:x))}
 async function compare(){setMsg('');if(sources.some(x=>!x.file))return setMsg('Selecione um ADIF para cada fonte.');const parsed=await Promise.all(sources.map(async x=>({name:x.name.trim().toUpperCase(),records:parseAdif(await x.file.text())})));const ref=parsed[reference];const pairs=[];for(let i=0;i<parsed.length;i++){if(i===reference)continue;const m=matchRecords(ref.records,parsed[i].records,ref.name,parsed[i].name);pairs.push({source:parsed[i].name,matched:m.matches.length,missing:m.unmatchedLeft.map(x=>x.raw),extra:m.unmatchedRight.map(x=>x.raw),review:m.reviews.length})}setResult({reference:ref.name,pairs});await appendActivity('COMPARE',`Comparação ADIF executada com ${parsed.length} fontes`,{sources:parsed.map(x=>x.name)})}
 return <div className="m9-tool"><div className="m9-tool-head"><div><h2>Comparar ADIF</h2><p>Auditoria manual com a mesma lógica de pareamento do mobile.</p></div><Button onClick={compare}>Comparar</Button></div>{msg&&<Notice tone="warn">{msg}</Notice>}<div className="m9-adif-list">{sources.map((s,i)=><article key={s.id} className={reference===i?'reference':''}><label><input type="radio" checked={reference===i} onChange={()=>setReference(i)}/> referência</label><input value={s.name} onChange={e=>patch(i,{name:e.target.value})}/><label className="m9-file">{s.file?.name||'Selecionar ADIF'}<input type="file" accept=".adi,.adif,.txt" onChange={e=>patch(i,{file:e.target.files?.[0]||null})}/></label>{sources.length>2&&<button onClick={()=>setSources(v=>v.filter((_,j)=>j!==i))}>remover</button>}</article>)}</div><Button kind="secondary" onClick={()=>setSources(v=>[...v,make('FONTE_'+(v.length+1))])}>+ fonte</Button>{result&&<div className="m9-compare-result">{result.pairs.map(p=><article key={p.source}><div><b>{result.reference} × {p.source}</b><small>{fmt(p.matched)} pareados · {fmt(p.review)} revisar</small></div><div><Badge tone="warn">{fmt(p.missing.length)} ausentes</Badge><Badge>{fmt(p.extra.length)} extras</Badge></div></article>)}</div>}</div>
}

export default function App900(){
 const [tab,setTab]=useState('overview'),[connections,setConnections]=useState({}),[datasets,setDatasets]=useState({}),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[progress,setProgress]=useState(''),[message,setMessage]=useState(''),[sheet,setSheet]=useState(null),[detail,setDetail]=useState(null),[search,setSearch]=useState(''),[issueFilter,setIssueFilter]=useState('ALL'),[toolTab,setToolTab]=useState('compare'),[activity,setActivity]=useState([])
 useEffect(()=>{Promise.all([loadConnections(),loadAllDatasets(KEYS)]).then(([c,d])=>{setConnections(c);setDatasets(d);setLoading(false)}).catch(e=>{setMessage('Erro: '+e.message);setLoading(false)})},[])
 const model=useMemo(()=>{const rows=consolidate(datasets,LOGS);const qsls=buildQsl(datasets.QRZ?.records||[],datasets.EQSL_INBOX?.records||[],datasets.LOTW?.records||[]);const issues=buildIssues(rows,qsls);return {rows,qsls,issues}},[datasets])
 const counts=useMemo(()=>Object.fromEntries(['MISSING','DIFFERENCE','DUPLICATE','QSL'].map(k=>[k,model.issues.filter(x=>x.type===k).length])),[model.issues])
 const filteredLog=useMemo(()=>{const q=search.trim().toUpperCase();return !q?model.rows:model.rows.filter(x=>[x.call,x.country,x.grid,x.band,x.mode].join(' ').toUpperCase().includes(q))},[model.rows,search])
 const filteredIssues=useMemo(()=>issueFilter==='ALL'?model.issues:model.issues.filter(x=>x.type===issueFilter),[model.issues,issueFilter])
 async function persist(p,result,next){const payload={records:result.records||[],updatedAt:new Date().toISOString(),metadata:result.metadata||{}};await saveDataset(p,payload);next[p]=payload;return payload}
 async function syncHrdlog(next,max=100){if(!configured('HRDLOG',connections,next)||!next.HRDLOG?.updatedAt||!next.QRZ?.records?.length)return {sent:0,remaining:0};const candidates=hrdlogPlan(next.QRZ.records,next.HRDLOG.records||[]);const batch=candidates.slice(0,max),known=[...(next.HRDLOG.records||[])];let sent=0;for(let i=0;i<batch.length;i++){setProgress(`HRDLog · ${i+1}/${batch.length}`);const q=batch[i];try{await pushHRDLog(connections.HRDLOG,next.QRZ.records[q.index]);known.push(next.QRZ.records[q.index]);sent++}catch{}await sleep(120)}const payload={records:known,updatedAt:new Date().toISOString(),metadata:{...(next.HRDLOG.metadata||{}),source:'bootstrap_plus_online',onlineManaged:true}};await saveDataset('HRDLOG',payload);next.HRDLOG=payload;if(sent)await appendActivity('SYNC',`HRDLog atualizado com ${sent} QSO(s)`);return {sent,remaining:Math.max(0,candidates.length-batch.length)}}
 async function syncAll(){if(syncing)return;setSyncing(true);setMessage('');const next={...datasets},errors=[];const jobs=[['QRZ',fetchQRZ,connections.QRZ],['WRL',fetchWRL,connections.WRL],['CLUBLOG',fetchClubLog,connections.CLUBLOG],['EQSL',fetchEQSL,connections.EQSL],['EQSL_INBOX',fetchEQSLInbox,connections.EQSL],['LOTW',fetchLoTW,connections.LOTW]];for(const [p,fn,c] of jobs){if(!configured(p,connections,next))continue;setProgress('Atualizando '+LABELS[p]+'…');try{const r=await fn(c);await persist(p,r,next);await appendActivity('SYNC',`${LABELS[p]}: ${r.records?.length||0} registros`)}catch(e){errors.push(`${LABELS[p]}: ${e.message}`)}}try{await syncHrdlog(next,100)}catch(e){errors.push('HRDLog: '+e.message)}setDatasets(next);setProgress('');setSyncing(false);setMessage(errors.length?`Concluído com ${errors.length} falha(s): ${errors.join(' | ')}`:'Todas as fontes atualizadas.')}
 async function syncOne(p){setSyncing(true);setProgress('Atualizando '+LABELS[p]+'…');setMessage('');try{const next={...datasets},map={QRZ:fetchQRZ,WRL:fetchWRL,CLUBLOG:fetchClubLog,EQSL:fetchEQSL,EQSL_INBOX:fetchEQSLInbox,LOTW:fetchLoTW},cred=p==='EQSL_INBOX'?connections.EQSL:connections[p],r=await map[p](cred);await persist(p,r,next);setDatasets(next);setMessage(`${LABELS[p]} atualizado: ${fmt(r.records?.length)} registros.`);await appendActivity('SYNC',`${LABELS[p]} atualizado`,{records:r.records?.length||0})}catch(e){setMessage('Erro: '+e.message)}finally{setProgress('');setSyncing(false)}}
 async function importAdif(p,file){if(!file)return;try{const records=parseAdif(await file.text());if(!records.length)throw new Error('Nenhum QSO válido no ADIF');const payload={records,updatedAt:new Date().toISOString(),metadata:{source:'manual_adif',filename:file.name,coverage:'FULL_EXPORT'}};await saveDataset(p,payload);setDatasets(v=>({...v,[p]:payload}));setMessage(`${LABELS[p]}: ${fmt(records.length)} QSOs importados.`);await appendActivity('IMPORT',`${LABELS[p]} importado`,{records:records.length,filename:file.name})}catch(e){setMessage('Erro: '+e.message)}}
 async function updateHrdlog(){setSyncing(true);try{const next={...datasets},h=await syncHrdlog(next,500);setDatasets(next);setMessage(h.sent?`HRDLog: ${h.sent} QSO(s) enviados/confirmados.`:'Nenhum QSO seguro pendente no HRDLog.')}catch(e){setMessage('Erro: '+e.message)}finally{setProgress('');setSyncing(false)}}
 async function exportAdif(){const lines=['<ADIF_VER:5>3.1.4','<PROGRAMID:19>PU2BRU-QSO-Manager','<EOH>',...model.rows.map(x=>recordToAdif(x.canonical))];download('PU2BRU-QSO-Manager-backup.adi',lines.join('\r\n'));await appendActivity('EXPORT',`Backup ADIF com ${model.rows.length} QSO(s)`)}
 async function exportJson(){const payload=await exportLocalBackup(KEYS);download('PU2BRU-QSO-Manager-backup.json',JSON.stringify(payload,null,2),'application/json;charset=utf-8');await appendActivity('EXPORT','Backup JSON local gerado')}
 async function showActivity(){setToolTab('activity');setActivity(await loadActivity(300))}
 if(loading)return <div className="m9-splash"><div>PU2<br/>BRU</div><h1>QSO Manager</h1><p>Montando seu workspace unificado…</p></div>
 const sourceCount=KEYS.filter(p=>configured(p,connections,datasets)).length
 return <div className="m9-app"><header className="m9-top"><div><small>PU2BRU · v{VERSION}</small><h1>QSO Manager</h1></div><button disabled={syncing} onClick={syncAll}>↻</button></header>{progress&&<div className="m9-progress">{progress}</div>}{message&&<div className={'m9-toast '+(message.startsWith('Erro')?'error':'')} onClick={()=>setMessage('')}>{message}<b>×</b></div>}<main>
 {tab==='overview'&&<section className="m9-page"><div className="m9-hero"><small>SEU LOG, UMA ÚNICA VERDADE</small><h2>{fmt(model.rows.length)}</h2><p>QSOs consolidados</p><div><span><b>{sourceCount}</b> fontes ativas</span><span><b>{fmt(model.qsls.length)}</b> com QSL</span></div></div><h3 className="m9-title">Precisa de atenção</h3><div className="m9-attention"><button onClick={()=>{setIssueFilter('MISSING');setTab('inbox')}}><i className="warn">−</i><span><b>{fmt(counts.MISSING)}</b>Ausentes</span></button><button onClick={()=>{setIssueFilter('DIFFERENCE');setTab('inbox')}}><i>≠</i><span><b>{fmt(counts.DIFFERENCE)}</b>Divergências</span></button><button onClick={()=>{setIssueFilter('DUPLICATE');setTab('inbox')}}><i>!</i><span><b>{fmt(counts.DUPLICATE)}</b>Duplicidades</span></button><button onClick={()=>setTab('qsl')}><i className="ok">✓</i><span><b>{fmt(counts.QSL)}</b>Confirmações</span></button></div><div className="m9-card"><header><div><h3>Fontes</h3><p>Mesma cobertura funcional do desktop</p></div><button onClick={()=>setTab('sources')}>Ver todas</button></header><div className="m9-source-strip">{KEYS.map(p=><button key={p} className={configured(p,connections,datasets)?'on':''} onClick={()=>setTab('sources')}><i>{SHORT[p]}</i><small>{datasets[p]?.records?.length?fmt(datasets[p].records.length):'—'}</small></button>)}</div></div><button className="m9-refresh" disabled={syncing} onClick={syncAll}>↻ <span><b>Atualizar tudo</b><small>Sincronizar APIs e recalcular o workspace</small></span></button></section>}
 {tab==='log'&&<section className="m9-page"><div className="m9-head"><small>LOG CONSOLIDADO</small><h2>Um QSO. Todas as fontes.</h2></div><div className="m9-search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Indicativo, país, grid, banda…"/>{search&&<button onClick={()=>setSearch('')}>×</button>}</div><div className="m9-qso-list">{filteredLog.slice(0,1500).map(q=><article key={q.id} onClick={()=>setDetail(q)}><div><span><h3>{q.call}</h3><p>{q.date} · {q.time.slice(0,4)} UTC</p></span><span className="m9-band"><b>{q.band}</b><small>{q.mode}</small></span></div><footer><div>{q.providers.map(p=><Badge key={p} tone={p==='QRZ'?'truth':'ok'}>{SHORT[p]}</Badge>)}{q.missingIn.map(p=><Badge key={p} tone="warn">−{SHORT[p]}</Badge>)}</div>{q.differences.length>0&&<Badge tone="warn">{q.differences.length} dif.</Badge>}</footer></article>)}</div>{!filteredLog.length&&<Empty title="Nenhum QSO encontrado"/>}{detail&&<DetailSheet row={detail} datasets={datasets} onClose={()=>setDetail(null)}/>}</section>}
 {tab==='inbox'&&<section className="m9-page"><div className="m9-head"><small>CAIXA DE ENTRADA</small><h2>Pendências</h2><p>Somente o que merece uma decisão.</p></div><div className="m9-chips">{[['ALL','Tudo',model.issues.length],['MISSING','Ausentes',counts.MISSING],['DIFFERENCE','Diferenças',counts.DIFFERENCE],['DUPLICATE','Duplicados',counts.DUPLICATE],['QSL','QSL',counts.QSL]].map(x=><button key={x[0]} className={issueFilter===x[0]?'active':''} onClick={()=>setIssueFilter(x[0])}>{x[1]} <b>{fmt(x[2])}</b></button>)}</div><div className="m9-issues">{filteredIssues.slice(0,1500).map((x,i)=><article key={i}><i className={x.type.toLowerCase()}>{x.type==='QSL'?'✓':x.type==='MISSING'?'−':'!'}</i><div><h3>{x.call}<span>{x.band} · {x.mode}</span></h3><p>{x.date} {String(x.time||'').slice(0,4)} · {x.message}</p></div></article>)}</div>{!filteredIssues.length&&<Empty title="Fila limpa"/>}</section>}
 {tab==='qsl'&&<section className="m9-page"><div className="m9-head"><small>CENTRAL DE QSL</small><h2>Confirmações com evidência</h2><p>eQSL Inbox + LoTW. A data do QSO nunca vira data de confirmação.</p></div><div className="m9-kpis"><div><b>{fmt(model.qsls.length)}</b><span>confirmados</span></div><div><b>{fmt(model.qsls.filter(x=>x.services.some(s=>s.kind==='LOTW')).length)}</b><span>LoTW</span></div><div><b>{fmt(model.qsls.filter(x=>x.services.some(s=>s.kind==='EQSL')).length)}</b><span>eQSL</span></div></div><div className="m9-qso-list">{model.qsls.slice(0,1500).map((q,i)=><article key={i}><div><span><h3>{q.call}</h3><p>{q.date} · {q.band} · {q.mode}</p></span><i className="m9-confirm">✓</i></div><footer className="qsl">{q.services.map((s,j)=><span key={j}><Badge tone="ok">{s.source}</Badge><small>{s.date||'recebido · data não informada'}</small></span>)}</footer></article>)}</div>{!model.qsls.length&&<Empty title="Sem confirmações sincronizadas">Atualize eQSL Inbox e LoTW.</Empty>}</section>}
 {tab==='sources'&&<section className="m9-page"><div className="m9-head"><small>FONTES</small><h2>Todas as conexões em um só lugar</h2><p>API, evidência QSL ou ADIF local — cada papel fica explícito.</p></div><div className="m9-source-list">{KEYS.map(p=>{const on=configured(p,connections,datasets),snap=datasets[p]||{},manual=['HRD','HRDLOG'].includes(p);return <article key={p}><button className="m9-source-open" onClick={()=>!manual&&setSheet(p)}><i className={on?'on':''}>{SHORT[p]}</i><div><h3>{LABELS[p]}</h3><p>{on?'Ativo':'Não configurado'} · {fmt(snap.records?.length)} registros</p><small>Atualizado: {when(snap.updatedAt)}</small></div><em>{manual?'':'›'}</em></button><div className="m9-source-actions">{p==='HRD'&&<label>{on?'Substituir ADIF':'Importar ADIF'}<input type="file" accept=".adi,.adif,.txt" onChange={e=>importAdif('HRD',e.target.files?.[0])}/></label>}{p==='HRDLOG'&&<><button onClick={()=>setSheet('HRDLOG')}>Conexão</button><label>Reconciliar ADIF<input type="file" accept=".adi,.adif,.txt" onChange={e=>importAdif('HRDLOG',e.target.files?.[0])}/></label><button disabled={!on||!snap.updatedAt||syncing} onClick={updateHrdlog}>Atualizar online</button></>}{!manual&&p!=='EQSL_INBOX'&&<button disabled={!on||syncing} onClick={()=>syncOne(p)}>Atualizar agora</button>}{p==='EQSL_INBOX'&&<button disabled={!on||syncing} onClick={()=>syncOne(p)}>Atualizar Inbox</button>}</div>{p==='HRDLOG'&&<p className="m9-provider-note">Bootstrap por ADIF + novos QSOs enviados online pelo Upload Code.</p>}{p==='HRD'&&<p className="m9-provider-note">No Android o log local do HRD entra via ADIF, com a mesma comparação usada no desktop.</p>}</article>})}</div></section>}
 {tab==='tools'&&<section className="m9-page"><div className="m9-head"><small>FERRAMENTAS</small><h2>Avançado sem poluir a jornada</h2></div><div className="m9-tool-tabs">{[['compare','Comparar ADIF'],['backup','Backup & export'],['activity','Atividade'],['security','Segurança']].map(x=><button key={x[0]} className={toolTab===x[0]?'active':''} onClick={()=>x[0]==='activity'?showActivity():setToolTab(x[0])}>{x[1]}</button>)}</div>{toolTab==='compare'&&<AdvancedCompare/>}{toolTab==='backup'&&<div className="m9-stack"><div className="m9-card"><h3>Backup ADIF consolidado</h3><p>{fmt(model.rows.length)} QSOs lógicos, um registro canônico por contato.</p><Button onClick={exportAdif}>Baixar ADIF</Button></div><div className="m9-card"><h3>Backup JSON do aplicativo</h3><p>Inclui snapshots e atividade local; credenciais nunca são incluídas.</p><Button kind="secondary" onClick={exportJson}>Baixar JSON</Button></div></div>}{toolTab==='activity'&&<div className="m9-activity">{activity.map(x=><article key={x.id}><Badge>{x.kind}</Badge><div><b>{x.message}</b><small>{when(x.at)}</small></div></article>)}{!activity.length&&<Empty title="Sem atividade registrada"/>}</div>}{toolTab==='security'&&<div className="m9-stack"><div className="m9-card"><h3>Credenciais</h3><p>No Android as chaves ficam no Secure Storage/Keystore quando disponível. Backups não incluem segredos.</p><div className="m9-security">{KEYS.filter(p=>!['HRD','EQSL_INBOX'].includes(p)).map(p=><p key={p}><span className={configured(p,connections,datasets)?'on':''}/><b>{LABELS[p]}</b><small>{configured(p,connections,datasets)?'configurada':'não configurada'}</small></p>)}</div></div><div className="m9-card"><h3>Paridade do produto</h3><p>Mesma jornada funcional do Windows: Log, Pendências, QSL, Fontes, comparação ADIF, HRD local por ADIF, HRDLog online e exportação.</p><Badge tone="ok">Windows = Android · v{VERSION}</Badge></div></div>}</section>}
 </main><nav className="m9-bottom">{NAV.map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}><i>{x[2]}</i><span>{x[1]}</span>{x[0]==='inbox'&&model.issues.length>0&&<em>{model.issues.length>99?'99+':model.issues.length}</em>}</button>)}</nav>{sheet&&<SourceSheet provider={sheet} connections={connections} onClose={()=>setSheet(null)} onSaved={async all=>{setConnections(all);setSheet(null)}}/>}</div>
}
