// End-to-end smoke test with synthetic QSOs only; run against an isolated data directory.
const {chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.QSO_CHROME_PATH,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const field=(k,v)=>`<${k}:${String(v).length}>${v}`;const record=(time,extra={})=>Object.entries({CALL:'LU1EEG',QSO_DATE:'20151028',TIME_ON:time,BAND:'20m',MODE:'JT65',FREQ:'14.076',...extra}).map(([k,v])=>field(k,v)).join('')+'<EOR>';
await page.goto('http://127.0.0.1:8000');await page.locator('nav button').filter({hasText:'Comparar ADI'}).click();
await page.getByRole('button',{name:'Adicionar ADIF',exact:true}).click();await page.getByLabel('Nome da fonte',{exact:true}).fill('QRZ setembro');await page.getByLabel('Arquivo ADIF',{exact:true}).setInputFiles({name:'qrz.adi',mimeType:'text/plain',buffer:Buffer.from(record('022300',{RST_SENT:'-10',EQSL_QSL_SENT:'Y'}))});await page.getByRole('button',{name:'Salvar fonte',exact:true}).click();await page.getByText('QRZ setembro',{exact:true}).first().waitFor();
await page.getByRole('button',{name:'Adicionar ADIF',exact:true}).click();await page.getByLabel('Nome da fonte',{exact:true}).fill('eQSL recebidos');await page.getByLabel('Conteúdo do arquivo').selectOption('EQSL_RECEIVED');await page.getByLabel('Arquivo ADIF',{exact:true}).setInputFiles({name:'eqsl.adi',mimeType:'text/plain',buffer:Buffer.from(record('022700',{EQSL_QSL_RCVD:'Y',EQSL_QSLRDATE:'20160203'}))});await page.getByRole('button',{name:'Salvar fonte',exact:true}).click();
await page.locator('nav button').filter({hasText:'Central de QSLs'}).click();const opts=await page.getByLabel('Log de referência').locator('option').evaluateAll(els=>els.map(x=>({text:x.textContent,value:x.value})));await page.getByLabel('Log de referência').selectOption(opts.find(x=>x.text.includes('QRZ setembro')).value);await page.locator('.wb-checks label').filter({hasText:'eQSL recebidos'}).getByRole('checkbox').check();await page.getByRole('button',{name:'Analisar confirmações',exact:true}).click();await page.getByRole('checkbox',{name:'Selecionar LU1EEG EQSL',exact:true}).check();await page.screenshot({path:'qsl-ui.png',fullPage:true});
const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Gerar ADIF revisado + evidências',exact:true}).click();const dl=await promise;await dl.saveAs('ui-qsl-revisado.zip');
await page.locator('nav button').filter({hasText:'Comparar ADI'}).click();await page.getByLabel('Log de referência').selectOption(opts.find(x=>x.text.includes('QRZ setembro')).value);await page.locator('.wb-checks label').filter({hasText:'eQSL recebidos'}).getByRole('checkbox').check();await page.getByRole('button',{name:'Comparar fontes',exact:true}).click();await page.getByRole('button',{name:'Exportar todos os achados (CSV)'}).waitFor();await page.screenshot({path:'comparison-ui.png',fullPage:true});if(errors.length)throw new Error(errors.join('\n'));console.log('UI import, QSL review/ZIP download and multi-source comparison passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)})
